"""
logger.py — Simulation result logging system.

This module provides functionality to save important simulation results,
methods, and metrics to a JSON log file, so past runs can be compared and the
model configuration tuned over time.
"""
import os
import json
import datetime
import logging
import numpy as np

def save_simulation_log(scen_name: str, result: dict) -> None:
    """
    Saves the key metrics and configuration of a successful simulation run.
    
    Args:
        scen_name (str): The name of the scenario.
        result (dict): The result dictionary generated by _run_scenario.
    """
    # Create logs directory if it doesn't exist
    log_dir = "logs"
    os.makedirs(log_dir, exist_ok=True)
    
    # Generate a unique timestamped filename
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = scen_name.replace(" ", "_").replace(":", "")
    filename = f"{log_dir}/{safe_name}_{timestamp}.json"
    
    # Prepare the log entry
    # We extract only serializable and highly informative details.
    log_data = {
        "scenario_name": scen_name,
        "timestamp": timestamp,
        "target_variable": result.get("target_col"),
        "metrics": {
            "r2_score": float(result.get("r2", 0.0)),
            "rmse": float(result.get("rmse", 0.0)),
            "training_time_seconds": float(result.get("train_time", 0.0)),
        },
        "model_details": {
            "type": type(result.get("model")).__name__ if result.get("model") else "Unknown",
            "n_features_used": int(result.get("n_features", 0)),
        },
        "feature_engineering": {
            "seasonal_features": bool(result.get("seasonal", True)),
        },
        "shap_insights": {}
    }
    
    # Include top SHAP features if available
    mean_shap = result.get("mean_shap")
    feat_names = result.get("feat_names")
    
    if mean_shap is not None and feat_names is not None:
        # Sort features by importance in descending order
        order = np.argsort(mean_shap)[::-1]
        top_features = [feat_names[i] for i in order]
        top_values = [float(mean_shap[i]) for i in order]
        
        log_data["shap_insights"] = {
            "top_features": top_features[:15], # Save up to top 15 features
            "top_shap_values": top_values[:15]
        }
        
    # Write the formatted data to a JSON file
    try:
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(log_data, f, indent=4)
        logging.info(f"Log saved successfully: {filename}")
    except Exception as e:
        logging.error(f"Failed to write log for {scen_name}: {e}")
